### ISSUE TITLE
periodic crashes when parsing config

### ISSUE THREAD

**Issue by jaredmauch** [NLnetLabs/nsd#11]
I've noticed some crashes in nsd apparently when parsing the config:

```
[1245276.933679] traps: nsd[22786] general protection fault ip:55ee2fdfc95b sp:7ffd63c299d8 error:0 in nsd[55ee2fde1000+5e000]
[1263776.965752] traps: nsd[9060] general protection fault ip:55ee2fdfc95b sp:7ffd63c299d8 error:0 in nsd[55ee2fde1000+5e000]
[1319575.155940] traps: nsd[20859] general protection fault ip:55ee2fdfc95b sp:7ffd63c299d8 error:0 in nsd[55ee2fde1000+5e000]
[1365798.607058] traps: nsd[23810] general protection fault ip:55ee2fdfc95b sp:7ffd63c299d8 error:0 in nsd[55ee2fde1000+5e000]
```

When looking at what is going on it seems to in the c_parse function:

```
(gdb) info line *0xc95b
Line 1654 of "configparser.c" starts at address 0xc93b <c_parse+203> and ends at 0xc95d <c_parse+237>.
(gdb) x/i 0xc95b
   0xc95b <c_parse+235>:	add    %al,(%rax)
```

I don't seem to have core files available for this, and it doesn't seem to crash in a way that takes the daemon down.  The reconfig command is issued every 5 minutes with a configuration file parsed from the database.

I can share the main config file and the include zone file as well in private.

**Comment by wcawijngaards** [comment]
Hi Jared,
Does the config file also crash when you then read it again, eg. by starting NSD again, or using nsd-checkconf?  If so, please send me those files so I can reproduce the issue.
If not, something must have happened, I would need to know more of the flaw, because line 1654 of configparser.c for me is a generic 'fetch data to parse' part, but perhaps you have different bison or version, if you get gdb to print the code line in C that would be helpful (in the case that the config file does not reproduce).

**Comment by jaredmauch** [comment]
yeah, i dunno.  I notice it in the system logs, and don't see any negative results in the cron outputs either.  I'm honestly a bit suspicious of the gdb results as well and would much prefer having a core file but don't see a good way to force the system to collect one.  (Let me poke around some more).

**Comment by jaredmauch** [comment]
As you saw from #15 i have cores established better now.  I'm not seeing this crashing at present.  If it occurs again, I will re-open a new issue.
