### ISSUE TITLE
AXFR restart when zone is updated

### ISSUE THREAD

**Issue by geertverheyen** [NLnetLabs/nsd#14]
If an update on the zone is received by NSD, and an AXFR of the zone is still running at that time, the AXFR transfer of the zone starts from the beginning of the zone again.
Therefore, certainly for a bigger zone, within the AXFR output, the first entries of the zone are shown mutiple times.
The AXFR output displays the following message when this happens:
`;; communications error to <ipaddress>#53: end of file`

**Comment by wcawijngaards** [comment]
It is your client that restarts the AXFR, prints this comment message, and concatenates the output of multiple AXFR attempts into one file.  If it was to print only the final result into the file, you would not have this problem.
I can tell, because AXFR does not continue across restarts and does not contain comments.  The format simply does not have them. NSD also does not insert that message into the output.  So it must be your AXFR client that does this.
Now, NSD can end the transfer in progress because the zone was updated, and this is certainly an issue itself.  But, I wanted to make sure you know where the different parts of the topic you are looking at are from.
`while ! drill <zone> AXFR @server > zonefile.zone; do echo "reattempt" ; done` (Or with dig instead of drill), I think that might retry and overwrite the file if the connection is closed due to an update.  I have not tested it.

**Comment by SvenVD-be** [comment]
Hi, we are aware  `;; communications error to #53: end of file` is inserted into the file by dig. 

But because we have IXFRs coming in every seconds, we are not able to successfully transfer an AXFR from nsd for a big zone, because it keeps restarting. So the main question is,  is this a known behavior or can this be fixed somehow?

We use the AXFR to do health checks on the zones on the slave (dnssec etc ..). We now have a workaround were we briefly block the master with iptables during AXFR, so far this is working fine. But we would prefer,  if possible, a fix in nsd.

Thanks

**Comment by jaredmauch** [comment]
I'm wondering if the zone has too much scale and there should be an additional zone cut at a boundary that makes sense?

**Comment by SvenVD-be** [comment]
No, the zone is a tld zone so no boundaries can be made

**Comment by wcawijngaards** [comment]
It is possible to throttle the restart speed of NSD with the nsd.conf option xfrd-reload-timeout: 100 that would insert 100 seconds between reloads.  In this way you can give yourself enough time for a transfer to complete.  If a change happens on its own it is applied straight away, it is changes bunched together that wait the timeout (in seconds).

**Comment by SvenVD-be** [comment]
Yes with the 100 seconds timeout and with a dig that retries we could also workaround the problem, but it is still a workaround (like our iptables). We were wondering if there could be a fix in nsd itself.


Besides that we rather would not want to wait 100 seconds at this point for a change to be applied by nsd (or are there changes were nsd does not need to reload?) 

Thanks for your advise

**Comment by wcawijngaards** [comment]
There is a commit that makes the connection linger and get serviced, in a process that hangs around for the purpose.  The timeouts of about 1/10 of a second and one second, are for packets to flow and events to happen.  If it is idle it gets disconnected.  This means the connections can finish.
I could restrict it to only AXFR, but right now the code handles TCP and TLS connections and gives them a chance to finish up.

**Comment by SvenVD-be** [comment]
So If I understand correctly, the fix works for when doing an AXFR  (tcp)? 

Thanks

**Comment by wcawijngaards** [comment]
Yes that is the intent.  And also for IXFR and over TLS too.

**Comment by SvenVD-be** [comment]
Any idea in which version this will be released?

**Comment by jaredmauch** [comment]
You just need to either git clone the head or the version with this commit and then build it - https://github.com/NLnetLabs/nsd/commit/d16a6093c03fc2a28765f4c11e8e410b1b17f213

**Comment by SvenVD-be** [comment]
We are using the EPEL rpms currently, we currently have a workaround for the issue in place so there is no urgency. We, however want to keep track of when this get released so we can remove the workaround. Thanks

**Comment by wcawijngaards** [comment]
4.2.1 looks like that is the next version.  It is under development.

**Comment by k0ekk0ek** [comment]
Updated some comments to remove special meaning of `#` as it was very confusing. Investigating further...
