### ISSUE TITLE
NODATA answers missin SOA in authority section after CNAME chain

### ISSUE THREAD

**Issue by pspacek** [NLnetLabs/nsd#142]
Version: nsd 4.3.2-1 on Arch, x86_64

SOA RR is missing in authority section of NODATA answers when NODATA happens to be at the end of a CNAME chain. This most likely leads to suboptimal caching (especially for non-existing AAAA).

Reproducer:
- [config_and_zone.zip](https://github.com/NLnetLabs/nsd/files/5574975/config_and_zone.zip)
- run `nsd -V5 -c nsd.conf -d`
- check that node exists:
```
$ dig @127.0.0.1 txt9.txt8.test. TXT
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50871
;; flags: qr aa rd; QUERY: 1, ANSWER: 2, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;txt9.txt8.test.			IN	TXT

;; ANSWER SECTION:
txt9.txt8.test.		9	IN	CNAME	txt10.txt9.txt8.test.
txt10.txt9.txt8.test.	10	IN	TXT	"TXT is the only type here"

;; AUTHORITY SECTION:
test.			878	IN	NS	ns.test.
```

- see that NODATA answer for a non-TXT type is missing SOA:
```
$ dig @127.0.0.1 txt9.txt8.test. A
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8644
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;txt9.txt8.test.			IN	A

;; ANSWER SECTION:
txt9.txt8.test.		9	IN	CNAME	txt10.txt9.txt8.test.
```

**Comment by wcawijngaards** [comment]
Hi fixed it.  This was purposefully present in a commit back from 2004.  I do not see a reason in rfc2308 to do it, so I did as you asked.  CNAMEs still make a difference because a delegation after a CNAME is treated differently, different AA flag and if the zone is not there, it is not an error code (the shorter CNAME only reply is returned with the partial answer that is available).

**Comment by pspacek** [comment]
Thanks, that was quick!

**Comment by wcawijngaards** [comment]
@pspacek  Petr can I ask you if the behaviour described in #140 is really what Knot does, eg. for a query of type CNAME the RCODE of the answer is NOERROR even if it ends in an NXDOMAIN.  But for type A the RCODE is set to NXDOMAIN when the CNAME chain ends on an NXDOMAIN node.  Is that what Knot does?  If so, I guess it is best if NSD does the same thing.

**Comment by libor-peltan-cznic** [comment]
@wcawijngaards Indeed, what Knot does is when you query a dangling into-bailiwick CNAME for AAAA, you get NXDOMAIN because the target name does not exist. If you query the same for the type CNAME however, then the CNAME itself is a good answer to the query, thus NOERROR (not NODATA!).

Recently, there has been an issue for both Knot and NSD about the situation where the CNAME is not in the zone, rather synthesized from a DNAME. In that case, it should behave the same, and it has been fixed in Knot few days ago. https://gitlab.nic.cz/knot/knot-dns/-/merge_requests/1217 It's just not yet released in any official version.

IMHO, your assumption that "NSD should behave the same as Knot" is not perfect enough. Let's cooperate constructively on finding the best solution, even when one is doing it wrong ;)
