### ISSUE TITLE
Zone(s) not synchronizing properly via TLS

### ISSUE THREAD

**Issue by cesarkuroiwa** [NLnetLabs/nsd#262]
We've been experiencing an issue where some zones are not
synchronizing properly from our primary server via TLS, mostly on
remote locations, where the connection tends to be unstable.

The scenario that we have able to reproduce is as follows:

- The primary server is running a proprietary solution serving about 140 zones
- NSD 4.6.1 is running as a secondary for all zones
- All transfers are done via TLS
- In order to simulate a poor connection, we manually added a 300ms
  delay and 10% packet loss on the client connection.

In this scenario, we noticed that some zones can't complete a zone
transfer (IXFR), probably due to unstable connection, and don't try
again at any moment later, even when receiving new notifies.

From the logfile, the msg that seems to be mostly related to this issue is:

```
[2023-01-24 19:35:19.858] nsd[14100]: error: ssl_read returned error 5 with received 0
[2023-01-24 19:35:19.858] nsd[14100]: error: xfrd: failed reading tcp Success
```

When queried for zonestatus, an out-of-sync zone appears to be in state "refereshing":
```
zone:    ecn.br
    state: refreshing
    served-serial: "2023023434 since 2023-01-23T18:05:17"
    commit-serial: "2023023434 since 2023-01-23T18:05:17"
    notified-serial: "2023023442 since 2023-01-23T18:25:16"
    transfer: "TCP connected to <primary IP>"
```

By running "netstat" both on the primary and secondary servers, there seems to be no open connection between the two.

Once it reaches this point, in order to make the zone synchronize
again, we have to run "nsd-control force_transfer".

**Comment by wcawijngaards** [comment]
From the code it looks like that could be a bug, since the output of the status shows it is TCP connected. At this point the code has a tcp handler with a file descriptor to that target. But if netstat shows it is not there, something must be wrong.

There is a timeout on this connection. It is configured as `tcp-timeout: 120` seconds. That is very large, and is from older RFCs. Perhaps a value like `tcp-timeout: 2` is better, much faster for current networks.

The timeout could be the only thing, not sure how that the notification of the connection should go; perhaps the shorter timeout needs to be adjusted with a new, lower default. Or msec capability for the setting.

**Comment by oroncoleta** [comment]
The issue persists even setting tcp-timeout to 2.

**Comment by wcawijngaards** [comment]
Reading up in the code. For ssl read failures. I noticed several issues, mostly the printout of the error that is wrong in your output, but that can be fixed a moment later. But then I saw an error where if the SSL connection reports that the channel is closed, it returns the wrong return value from the function. Causing the event to stay in existence for a connection that is not going to do anything any more. And this sounds suspiciously similar to what you are reporting. It is not identical to the log lines that you quoted, it would have printed nothing for this case, but with the fix it should print the 'xfrd: failed reading tcp' line. And also close the connection due to the failure.

The diff for it is this. Perhaps I should also commit it, would that be helpful?

```diff
diff --git a/xfrd-tcp.c b/xfrd-tcp.c
index b5910b33..f07cccb1 100644
--- a/xfrd-tcp.c
+++ b/xfrd-tcp.c
@@ -1268,7 +1268,7 @@ conn_read_ssl(struct xfrd_tcp* tcp, SSL* ssl)
                        }
                        if(err == SSL_ERROR_ZERO_RETURN) {
                                /* EOF */
-                               return 0;
+                               return -1;
                        }
                        log_msg(LOG_ERR, "ssl_read returned error %d with received %zd", err, received);
                }
@@ -1317,7 +1317,7 @@ conn_read_ssl(struct xfrd_tcp* tcp, SSL* ssl)
                int err = SSL_get_error(ssl, received);
                if(err == SSL_ERROR_ZERO_RETURN) {
                        /* EOF */
-                       return 0;
+                       return -1;
                }
                log_msg(LOG_ERR, "ssl_read returned error %d with received %zd", err, received);
        }
```

Does this patch make the problem less severe?

**Comment by cesarkuroiwa** [comment]
Hi, we tested this patch in our lab environment and it really seems to have improved a lot. Now, even if some zones fail to transfer in a publication, these seem to sync right in the next pub.

Thanks a lot!

**Comment by wcawijngaards** [comment]
Nice to hear that it works. That means the commit is the fix for the issue!

For the debug log output, that seems to need some more looking at to improve it.
