### ISSUE TITLE
Large TXT record breaks AXFR

### ISSUE THREAD

**Issue by jrlevine** [NLnetLabs/nsd#273]
This zone file has an almost 32K TXT record. It loads and serves fine, but AXFR fails when it gets to that record.

https://www.taugh.com/johnlevine.com.zone

Running the FreeBSD package of 4.6.1

**Comment by wcawijngaards** [comment]
This was a problem with NSD since a longer time, it is for records larger than 16K. The fix allows such a record as the first and only RR in a message in the stream of axfr, or ixfr, messages. This allows the transfer to complete successfully from nsd to the client.

The limit for 16K was used to keep the messages within the limits where name compression can be used, this makes transfers smaller. It is also used with the fix, when records fit within that limit.
