### ISSUE TITLE
dnstap_collector.c: SOCK_NONBLOCK is not available on Mac/Darwin

### ISSUE THREAD

**Issue by ljliman** [NLnetLabs/nsd#284]
Hi guys!

Thanks for keeping up the fantastic work.

While trying to compile NSD with dnstap support on a Mac I ran into:

% make
gcc -I/opt/pkg/include -I. -I/opt/pkg/include -L/opt/pkg/include -c dnstap/dnstap_collector.c
clang: warning: argument unused during compilation: '-L/opt/pkg/include' [-Wunused-command-line-argument]
dnstap/dnstap_collector.c:68:39: error: use of undeclared identifier 'SOCK_NONBLOCK'
                if(socketpair(AF_UNIX, SOCK_DGRAM | SOCK_NONBLOCK, 0, sv) < 0) {
                                                    ^
1 error generated.
make: *** [dnstap_collector.o] Error 1

... and alas, SOCK_NONBLOCK doesn't exist on the Macs. I see you have worked around it in other parts of the code. Would you please "do the same" in the dnstap corner?

This is with nsd-4.7.0 and MacOS Monterrey (12.6).

Cheers,
  /LIman

**Comment by wcawijngaards** [comment]
The -L compile argument with an include directory looks unnecessary to me, usually -L needs a library directory. But I guess otherwise harmless, as there is likely no libraries there.

The commit applies a similar fix that exists in other parts of the code. It ignores the extra argument if that option does not exist, and then attempts to set nonblocking with the fcntl function. Thanks for the fail details, I hope it works on the compile environment, but that seems likely.

**Comment by ljliman** [comment]
Hi Wouter!

Thanks for a quick fix. It does indeed take me through compilation like a breeze. Next I'll test the functionality.

I'm a bit surprised that you didn't identify the "-L" as the obvious cut-and-paste error that it is though, but thanks for highlighting it.

Cheers,
  /Liman
