### ISSUE TITLE
bundled configure file for 4.9.0 release is problematic

### ISSUE THREAD

**Issue by chenrui333** [NLnetLabs/nsd#321]
👋 while trying to bump nsd to the latest release, I noticed that the bundled configure file has some issue, ie missing `config.guess` and `config.sub`

See build log https://github.com/Homebrew/homebrew-core/actions/runs/8541222556/job/23400295300

relates to https://github.com/Homebrew/homebrew-core/pull/167891

cc @k0ekk0ek

**Comment by oukb** [comment]
The error with the archive
https://www.nlnetlabs.nl/downloads/nsd/nsd-4.9.0.tar.gz

`configure: error: cannot find required auxiliary files: config.guess config.sub`

As a temporary solution before `configure` do `autoreconf -fi`

Version https://www.nlnetlabs.nl/downloads/nsd/nsd-4.8.0.tar.gz - ok

**Comment by chenrui333** [comment]
> As a temporary solution before `configure` do `autoreconf -fi`

yeah, that is what I am doing, just want to raise an issue in here for awareness.

**Comment by k0ekk0ek** [comment]
Hi @chenrui333, @oukb! Indeed, the auxiliary files are missing. #319 meant to fix the `makedist.sh` script on my machine, but it did not get merged and when I ran the `configure` script from the tarball it worked without issue. I'm not sure why it did not show, maybe it's because the files were in a parent directory. I'll check with the other devs if we want to do a 4.9.1 right away. In any case, I'll be adding CI tests to avoid this in the future. Thanks for reporting the issue :+1:

**Comment by k0ekk0ek** [comment]
We've released 4.9.1. Also, I've updated the `makedist.sh` script to use a separate directory to make the release tarball, so this shouldn't happen again. Thanks for reporting!

**Comment by chenrui333** [comment]
sounds great, thanks for the quick turnaround!
