### ISSUE TITLE
Feature Request: RFC2136 aka DNS  Update support for nsd

### ISSUE THREAD

**Issue by debdrup** [NLnetLabs/nsd#34]
Since nsd is an authoritative DNS intended as a replacement for ISC bind, would it be possible that at some point it can gain the Dynamic DNS facility that bind supports and which is specified by RFC2136?

Please note that I'm not asking for unbound to gain this facility, despite the fact that it is local-authoritative - [as it seems pretty clear that it will not be added](https://github.com/NLnetLabs/unbound/blob/cd0a2b1af1a9d75ac09e1719ce9a6c76a5e638ae/doc/FEATURES#L31).

**Comment by wcawijngaards** [comment]
This would need a zone signer to be able to handle DNSSEC.  So, what we previously told people is that you can run OpenDNSSEC.  Then feed dynamic updates into that, use it for the signing functionality and then feed the result into nsd (or a collection of nameservers) to serve the data.
NSD does support IXFR, i.e. incremental updates, if this is about making incremental changes that tie into some other system.  I'll close this since we do not have the intent, eg. use OpenDNSSEC as a signer, and feed the changes to there.
