### ISSUE TITLE
are flex and bison still required?

### ISSUE THREAD

**Issue by lemire** [NLnetLabs/nsd#340]
Now that nsd has adopted simdzone, does it still require flex/bison?

@k0ekk0ek

**Comment by k0ekk0ek** [comment]
Hi @lemire. Unfortunately, yes. The configuration parser in NSD still requires those. Personally, I would like to see that requirement gone, but for now those tools are still needed. For users though, they're not really impacted because it's a build-time requirement and in the release tarballs we ship the generated sources.
