### ISSUE TITLE
Inconsistent documentation about control-interface

### ISSUE THREAD

**Issue by melroy89** [NLnetLabs/nsd#392]
I'm running Ubuntu Server 24.04 (LTS), which comes with  NSD v4.8.0.

The documentation and manpage are stated that:

1. Remote control (aka. `control-enable`) is disabled by default, [see documentation here](https://nsd.docs.nlnetlabs.nl/en/latest/manpages/nsd.conf.html?highlight=control+enable#control). While it seems to be enabled in my case by default..
2. That the control interface (aka  `control-interface`) is only listening on `127.0.0.1` according to [the `man nsd.conf` page here](https://github.com/NLnetLabs/nsd/blob/a922e4bae9a0c1811c7dd0b1723248ab88fc54e0/doc/manual/configuration.rst?plain=1#L61), while in my case again it's clearly also listing on IPV6: `::1`. I think the webpage documentation is saying this correctly, but not the manpage..

I notice all of the above misalignment issues between real-world production & documentation, because I disabled IPV6 in my sysctl:

```ini
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```

That is why I get:

```sh
Oct 23 16:28:10 ubuntu-server nsd[3389096]: nsd starting (NSD 4.8.0)
Oct 23 16:28:10 ubuntu-server nsd[3389096]: can't bind tcp socket: Cannot assign requested address
Oct 23 16:28:10 ubuntu-server nsd[3389096]: cannot open control interface ::1 8952
Oct 23 16:28:10 ubuntu-server nsd[3389096]: could not open remote control port
Oct 23 16:28:10 ubuntu-server nsd[3389096]: could not perform remote control setup
Oct 23 16:28:10 ubuntu-server systemd[1]: nsd.service: Main process exited, code=exited, status=1/FAILURE
```

Changing the `nsd.conf` configuration to use:

```conf
remote-control:
        control-interface: 127.0.0.1
```

Actually resolves the above issue, and NSD will start successfully. And yes, port 8952 is listening, so remote control is enabled under Ubuntu Server 24.04 at least by default:

```sh
sudo netstat -punta | grep 8952
tcp        0      0 127.0.0.1:8952          0.0.0.0:*               LISTEN      3403073/nsd   
```

ps. I'm unable to pick specific version of the documentation, so I can only see 'latest':

![image](https://github.com/user-attachments/assets/e74756b1-ae12-4b56-9d19-41b0ffc03dd8)

**Comment by melroy89** [comment]
I didn't create a PR (yet), since I would like to know the following:

1. Should NSD by default use remote control? If yes, then update documentation. If not, then update the code.
2. Should NSD control interface listen also on IPV6 by default? If yes, also update the man page (manual). If not, update the code.

**Comment by wcawijngaards** [comment]
NSD has remote control disabled by default. This is the default in the source code. But distributions sometimes set options in config files that are placed in, like /etc/nsd.. locations. That could have options set. Like where the pidfile is located, the username to use, directory to use, and also if remote control is enabled.

The remote control, if not set with an option to use an interface, uses 127.0.0.1 if do-ip4 is enabled, and also ::1 if do-ip6 is enabled. The option `do-ip6: no` could be useful, if ip6 is disabled, as then remote control would not attempt to make an IPv6 interface. Or set the interface for remote-control with `control-interface: 127.0.0.1` to an IPv4 address. That should stop it from making a ::1 socket.

I do not really think a documentation update for the NSD options is helpful here. The remote control should be disabled by default, so not a change in the code either. The disable by default is for security. As far as I can tell the issue is options set by the distribution, perhaps? Or where could be options otherwise be coming from? What config files does it read? The config file location can be set at compile time, so it can be located in another place. But the NSD documentation does not set the options that distributions include, or it would then be wrong for a different distribution.

**Comment by wcawijngaards** [comment]
After some browsing, I believe that the version that is used has a patch to enable remote-control in the source compile, with a patch applied by the distribution to the source when a package is compiled. This sets a different default, with control-enable: yes. That must be why it is enabled, and why NSD then, with do-ip6 also at a default of yes, tries to have a ::1 socket.

If you set the values of the config options to the value that is wanted, then it should work fine. I do not make the packages, eg. the distribution, of the code, so I can not talk about changes to that.

**Comment by melroy89** [comment]
> After some browsing, I believe that the version that is used has a patch to enable remote-control in the source compile, with a patch applied by the distribution to the source when a package is compiled. This sets a different default, with control-enable: yes. That must be why it is enabled, and why NSD then, with do-ip6 also at a default of yes, tries to have a ::1 socket.

OK that make sense, I also don't see any other way why this would otherwise be enabled by default under Ubuntu.

>  Or set the interface for remote-control with control-interface: 127.0.0.1 to an IPv4 address. That should stop it from making a ::1 socket.

Yes, I know that is what I said in my first comment, that is what I currently have configured now in order to start it.

---

@wcawijngaards  still one question remains unanswered, https://nsd.docs.nlnetlabs.nl/en/latest/manpages/nsd.conf.html?highlight=control+enable#control is saying that "If none are given NSD listens to the localhost 127.0.0.1 and ::1 interfaces for control", meaning the default seems to be IPv4 + IPv6, and again the manpage says only https://github.com/NLnetLabs/nsd/blob/a922e4bae9a0c1811c7dd0b1723248ab88fc54e0/doc/manual/configuration.rst?plain=1#L61 IPV4 is the default.

So what is correct? If you ignore Ubuntu for a second, there is still a difference in both documentation pages.

**Comment by wcawijngaards** [comment]
That is wrong, the default is 127.0.0.1 and ::1, I updated that with the fix commit. That should document the default for control interfaces for NSD consistently with what it does, and what is noted in the man page.

**Comment by melroy89** [comment]
> That is wrong, the default is 127.0.0.1 and ::1, I updated that with the fix commit. That should document the default for control interfaces for NSD consistently with what it does, and what is noted in the man page.

Thanks for the fix! Clear.
