### ISSUE TITLE
Massive error logging under heavy server load

### ISSUE THREAD

**Issue by salzmdan** [NLnetLabs/nsd#52]
When the server is unable to respond all queries due to saturated network, it emits plenty of logs:

```
[2019-11-25 13:26:59.379] nsd[146817]: error: sendto 192.168.200.20 failed: Resource temporarily unavailable
```

Verbosity logging level: **default**

**Comment by wcawijngaards** [comment]
Hi Daniel,
The error refers to operating system buffers that are insufficient.  I.e. the network stack has too little buffers to accomodate the system calls that the application is making.  I think it is good to print them, because your server is not working. (or, not working well).  The solution is to increase buffer availability.  I.e. increase memory.  Or increase buffer sizes.  Perhaps increase the settings send-buffer-size and receive-buffer-size in nsd.conf, I suggest 4000000 or 8000000 (4m or 8m or so).  On some systems NSD could be hampered from setting these values by permissions, eg. security capabilities that it needs to make that socket call.

I figure this may be the best solution so you do not have packet drops because the server is out of buffer space.

Best regards, Wouter

**Comment by wcawijngaards** [comment]
However, I see you say that the network is saturated, and if that is the case, that may cause the buffers to overflow and then this to tell the application that packets cannot get sent.  In that case, I am not sure, how to deal with the error, I mean.  Sometimes it is useful but not at that time, is this what is happening?  Or is it a spike in traffic that just needs bigger buffers?  Perhaps that solution could be described in documentation or the log is too awkward in an actual operational situation?

**Comment by salzmdan** [comment]
Hi Wouter,
I understand your explanation. I have a powerful server which is able to respond all queries but 10GbE is the bottleneck. The network cannot transmit more responses because they are bigger (DNSSEC) than the queries. Then the server emits a 1 GiB log file in 10 seconds. I think it's similar to the situation when the server cannot receive more queries. They are simply dropped without logging. So if there was no error log, I would be happy. What about using a weaker log severity level, which would be ignored if **verbosity: 0**? But it's up to you. It's not a usual situation.

**Comment by wcawijngaards** [comment]
I upped the verbosity for the errors, also several other errno values. This fixes your issue.

Unbound retries with blocking mode set on the file descriptor, when the network is full.  This makes it wait until the network can accept packets again.  I am not sure if this is what you want, if so, that could be added here.

**Comment by salzmdan** [comment]
The verbosity fix is enough. Thank you!
