### ISSUE TITLE
Any tips for compiling on linux

### ISSUE THREAD

**Issue by teknopaul** [NLnetLabs/nsd#65]
Hi NetLabs,

I'm trying to build a version with as few dependencies as pos for LXC containers, (esp systemd)

Any tips for building in Linux?

So far I have

```
apt install flex bison
$ ./configure \
   --enable-systemd=no \
   --enable-ipv6=no \
   --enable-dnstap=no \
   --enable-bind8-stats=no \
   --enable-zone-stats=no \
   --enable-nsec3=no
make
```

This gives me

```
ldd nsd
	linux-vdso.so.1 (0x00007ffc9a71d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb6524c9000)
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007fb652437000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007fb652162000)
	libevent-2.1.so.6 => /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6 (0x00007fb651f11000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb652796000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb651eee000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb651ee8000)
```

this is good enough, but wondering if there is anything I can do to get rid of SSL deps since I'm not using DNSSEC.

**Comment by teknopaul** [comment]
```
./configure \
   --enable-systemd=no \
   --enable-ipv6=no \
   --enable-dnstap=no \
   --enable-bind8-stats=no \
   --enable-zone-stats=no \
   --enable-nsec3=no \
   --with-libevent=no \
   --with-ssl=no 
```

gives me

```
ldd nsd
	linux-vdso.so.1 (0x00007ffcea1f7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f57fc828000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f57fcab0000)
```

I dont suppose its possible to compile a statically bound bin is it?

**Comment by wcawijngaards** [comment]
Yes that is about as short as possible I guess.  So there are no configure switches for static compilation like unbound has, but you can add it yourself.

Linking is done by the `LINK=` line in Makefile. You can add custom options there.  The `$(LDFLAGS)` is used like normal, and this is settable from configure.  With something like `./configure ... LDFLAGS="-static"`, then in Makefile the `LDFLAGS=` should change into a line that includes the `-static` option.

Instead of `-static` use the option `-all-static` for even more statically linked.  This I think gives executables that are suitable for some environments where you need as little as possible.

Best regards, Wouter

**Comment by teknopaul** [comment]
Hi Wouter,  thanks,

For the record:  Ubuntu 19.10

`-static` complains a bit

    warning: Using 'getservbyname' in statically linked applications requires at run time the shared libraries from the glibc version used for linking.

That's probably OK.

19.10 does not have `-all-static` in gcc

    unrecognized command line option ‘-all-static’; did you mean ‘--static’?

`musl-gcc`  (apt install musl-dev) with `-static` gives me

	ldd nsd
	    not a dynamic executable

Running `nsd` from head of git, livin' on the edge :)

**Comment by wcawijngaards** [comment]
Looks good, so `-static` solves your problem, with `musl-gcc`?  That is good to hear, want to close the issue?

**Comment by teknopaul** [comment]
yes, of course,sorry, thanks for input.
