### ISSUE TITLE
Configuration mangers (ansible, chef, puppet, salt, wffls) candidates for contrib?

### ISSUE THREAD

**Issue by bbros-dev** [NLnetLabs/nsd#68]
Are configuration mangers candidates for `contrib`: ansible, chef, puppet, salt, wffls?

It would likely only make sense if they were included as [sub-repos](https://github.com/ingydotnet/git-subrepo)

The purpose (benefit) would be to record and coalesce best practices, share these between the various tools and improve default setups.

**Comment by wcawijngaards** [comment]
No, not sub-repos.  But configuration and management is fine for contrib, everything is, and that certainly.  Perhaps more useful is an actual link (http) to the url where the configuration manager can be found, or a quick sample in some cases and then links.  For example, the statistics scripts and startup scripts and packaging scripts in contrib are often modified or used as a base to build upon.  For that, some (minimal) sample framework for a configuration manager would be good for contrib.  The project that is more detailed manager for that sounds better to have a url link to where that can be found, as its separate project and tasks.  Also imagine that for packaging, that would have to end up in a separate install package anyway, just like libs, statistics and script hooks, so for contrib a link to the information is just as good for the source compile users.  We would certainly not want, for packaging, end up in a situation where the server package depends on all the configuration managers packages, but that separate package, or url link in contrib could.  Because then during install it would insist on installing all of them.

**Comment by k0ekk0ek** [comment]
Let's close this one. @bbros-dev gave a thumbs-up on the answer.
